updateDocsWhiteList:
  - BUG
  - Chore
  - minor

updateDocsComment: >
  隆Gracias por abrir esta solicitud de extracci贸n (pull request)! Los mantenedores de este repositorio agradecer铆an que actualizara parte de nuestra documentaci贸n en funci贸n de sus cambios.

requestInfoReplyComment: >
  隆Le agradecer铆amos que nos pudiera proporcionar m谩s informaci贸n sobre esta incidencia/pr!

requestInfoLabelToAdd: request-more-info

newIssueWelcomeComment: >
  隆Gracias por abrir esta incidencia! Un miembro de Coderic Latam deber铆a venir pronto para darnos su opini贸n. Mientras tanto, consulte las [directrices de contribuci贸n](https://github.com/CodericLatam/.github/blob/main/CONTRIBUTING.md).
newPRWelcomeComment: >
  隆Gracias por abrir esta solicitud de extracci贸n (pull request)! Un miembro del Coderic Latam deber铆a venir pronto para darnos su opini贸n. Mientras tanto, consulte las [directrices de contribuci贸n](https://github.com/CodericLatam/.github/blob/main/CONTRIBUTING.md).
firstPRMergeComment: >
  隆Felicitaciones por fusionar su primera solicitud de extracci贸n! 隆Estamos orgullosos de usted!

sentimentBotToxicityThreshold: .7

sentimentBotReplyComment: >
  Aseg煤rese de revisar el c贸digo de conducta y ser respetuoso con los dem谩s usuarios.. cc/ @hiimbex

lockThreads:
  toxicityThreshold: .7
  numComments: 2
  setTimeInHours: 72
  replyComment: >
    Este hilo est谩 bloqueado debido a que se exceden los m铆nimos de toxicidad. cc/ @hiimbex
