newIssueWelcomeComment: >
  隆Gracias por abrir esta incidencia! Un miembro de Coderic Latam deber铆a venir pronto para darnos su opini贸n. Mientras tanto, consulte las [directrices de contribuci贸n](https://github.com/CodericLatam/.github/blob/main/CONTRIBUTING.md).
newPRWelcomeComment: >
  隆Gracias por abrir esta solicitud de extracci贸n (pull request)! Un miembro del Coderic Latam deber铆a venir pronto para darnos su opini贸n. Mientras tanto, consulte las [directrices de contribuci贸n](https://github.com/CodericLatam/.github/blob/main/CONTRIBUTING.md).
firstPRMergeComment: >
  隆Felicitaciones por fusionar su primera solicitud de extracci贸n! 隆Estamos orgullosos de usted!