blank_issues_enabled: false
contact_links:
  - name: "ğŸ’¬ Discusiones"
    url: https://github.com/orgs/CodericLatam/discussions
    about: Proponga nuevas ideas, brinde comentarios o solicite ayuda aquÃ­
  - name: "Canal en WhatsApp"
    url: https://whatsapp.com/channel/0029Va7We7SFnSzFCwTi8R1C
    about: Puede mantenerse informado en el canal de WhatsApp
  - name: "â“ Solicite ayuda desde el grupo en WhatsApp"
    url: https://chat.whatsapp.com/JvwyXjsKKw20j1ruSW9f30
    about: Puede hacer cualquier consulta urgente en el grupo en WhatsApp
  - name: ğŸ“ Grupo en Facebook
    url: https://www.facebook.com/groups/codericteam/
    about: Puedes abrir debates de discusiÃ³n o consultas en el grupo en Facebook
  - name: "ğŸ“– DocumentaciÃ³n"
    about: "Consulte primero la documentaciÃ³n de Coderic Latam antes de abrir nuevas incidencias o hacer preguntas."
    url: https://es.coderic.org/docs/
